/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

using System;

namespace HelloWorld
{
    class Program
    {
      static void Main(string[] args)
      {
        string s = "test";
        string t = "twest";

        char result = FindTheDifference(s,t);
        Console.WriteLine(result);
      }


      public class Solution {
          public char FindTheDifference(string s, string t) {
              if(s.Length == 0)         
              return t[0];
              
              foreach (char c in t) {
                      if (t.Count(ch => ch == c) > s.Count(ch => ch == c)) {
                          return c;
                      }
                  }
              return '\0';
          }
      }
    }
}
